excluded:
  - Carthage
  - Legacy
  - LibSpotijack/Scripting Bridge Compatibility

opt_in_rules:
  - closure_end_indentation
  - closure_spacing
  - fatal_error_message
  - operator_usage_whitespace
  - overridden_super_call
  - private_outlet

disabled_rules:
  - unused_capture_list

line_length:
  warning: 150
  ignores_function_declarations: true

identifier_name:
  excluded:
    - id

  allowed_symbols: ["_"]
  validates_start_with_lowercase: false
